# Generated by Django 5.2.7 on 2025-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternate_user_type',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('artisan', 'Artisan')], max_length=10, null=True),
        ),
    ]
