# Generated by Django 5.2.7 on 2025-10-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_alternate_user_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'user_type')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='alternate_user_type',
        ),
    ]
