# Generated by Django 5.2.7 on 2025-10-19 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePictureUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The uploaded profile picture', upload_to='profile_pictures/confirmations/')),
                ('is_confirmed', models.BooleanField(default=False, help_text='Whether the profile picture has been confirmed and applied')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(help_text='The user who uploaded the profile picture', on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Picture Upload',
                'verbose_name_plural': 'Profile Picture Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
